version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            FLASK_DEBUG: 'True'
            FLASK_ENV: development
            ENV: __dev__
        # depends_on:
            # - redis
    # redis:
        # image: redis